version: '3.3'

services:
  nginx:
    hostname: nginx
    container_name: nginx-security
    image: nginx:1.13
    restart: always
    ports:
      - "90:90"
      - "554:554"
    depends_on:
      - app
  app:
    hostname: app
    image: 'security/app'
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true